#!/bin/zsh
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=true

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then
      success "skipped $source"

    else
      link_files $source $dest
    fi

  done
}

# setup_gitconfig
install_dotfiles




# If we are on a mac, lets install and setup homebrew
if [[ "$(uname -s)" == "Darwin" ]]
then
  info "installing dependencies \n"
  if $HOME/.bin/dot > /tmp/dotfiles-dot 2>&1
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

if [[ "$(uname -s)" == "Darwin" ]]
then
  info "installing fonts \n"
  cp $DOTFILES_ROOT/fonts/* ~/Library/Fonts/
fi


if [[ "$TERM" == "xterm-256color" ]]
then
  success "\$TERM var set properly for good vim colours!"
else
  fail "Your \$TERM isn't set to xterm-256color. Set it to that so that vim colours work. see http://stackoverflow.com/questions/7424037/why-dont-git-colors-show-up-in-iterm2"
fi


info "Installing/updating vim config"
curl http://j.mp/spf13-vim3 -L -o - | sh

echo ''
echo '  All installed!'


